local M = {}

local CURRENT_CALL_NAMES = {
  ["and"] = true,
  ["array"] = true,
  ["call"] = true,
  ["capture_between"] = true,
  ["capture_from"] = true,
  ["capture_len_between"] = true,
  ["capture_len_from"] = true,
  ["capture_rest"] = true,
  ["capture_rest_from"] = true,
  ["capture_rest_len"] = true,
  ["capture_rest_len_from"] = true,
  ["capture_slice"] = true,
  ["capture_slice_col"] = true,
  ["capture_slice_len"] = true,
  ["capture_slice_line"] = true,
  ["capture_slice_pos"] = true,
  ["capture_slice_until_cursor"] = true,
  ["capture_slice_until_cursor_len"] = true,
  ["capture_take"] = true,
  ["capture_take_between"] = true,
  ["capture_take_between_len"] = true,
  ["capture_take_len"] = true,
  ["capture_take_len_from"] = true,
  ["capture_take_rest"] = true,
  ["capture_take_rest_from"] = true,
  ["capture_take_rest_len"] = true,
  ["capture_take_rest_len_from"] = true,
  ["capture_take_until_cursor"] = true,
  ["capture_take_until_cursor_from"] = true,
  ["capture_take_until_cursor_len"] = true,
  ["capture_take_until_cursor_len_from"] = true,
  ["capture_until_boundary"] = true,
  ["capture_until_cursor_from"] = true,
  ["capture_until_cursor_len_from"] = true,
  ["case"] = true,
  ["cat"] = true,
  ["clear_mark"] = true,
  ["coalesce"] = true,
  ["coalesce_nonempty"] = true,
  ["concat_arrays"] = true,
  ["contains"] = true,
  ["contains_substr"] = true,
  ["copy"] = true,
  ["count"] = true,
  ["count_keys"] = true,
  ["cursor_col"] = true,
  ["cursor_line"] = true,
  ["cursor_pos"] = true,
  ["cursor_rest"] = true,
  ["cursor_rest_len"] = true,
  ["default"] = true,
  ["drop_back"] = true,
  ["drop_front"] = true,
  ["drop_keys"] = true,
  ["else"] = true,
  ["elseif"] = true,
  ["endcase"] = true,
  ["endif"] = true,
  ["ends_with"] = true,
  ["endswitch"] = true,
  ["entry_col"] = true,
  ["entry_end_col"] = true,
  ["entry_end_line"] = true,
  ["entry_end_pos"] = true,
  ["entry_group"] = true,
  ["entry_groups"] = true,
  ["entry_has"] = true,
  ["entry_len"] = true,
  ["entry_line"] = true,
  ["entry_map"] = true,
  ["entry_named"] = true,
  ["entry_start_col"] = true,
  ["entry_start_line"] = true,
  ["entry_start_pos"] = true,
  ["entry_text"] = true,
  ["exit_now"] = true,
  ["filter_match"] = true,
  ["filter_nonempty"] = true,
  ["first"] = true,
  ["flat"] = true,
  ["flat_array"] = true,
  ["flat_hash"] = true,
  ["has_key"] = true,
  ["hash"] = true,
  ["if"] = true,
  ["index_of"] = true,
  ["input_end_col"] = true,
  ["input_end_line"] = true,
  ["input_end_pos"] = true,
  ["input_len"] = true,
  ["input_slice"] = true,
  ["input_text"] = true,
  ["is_defined"] = true,
  ["is_empty"] = true,
  ["is_nonempty"] = true,
  ["is_undefined"] = true,
  ["join_values"] = true,
  ["last"] = true,
  ["length"] = true,
  ["lowercase"] = true,
  ["lowercase_each"] = true,
  ["map_leaves"] = true,
  ["mark_capture_slice"] = true,
  ["mark_col"] = true,
  ["mark_copy"] = true,
  ["mark_entry_end"] = true,
  ["mark_entry_start"] = true,
  ["mark_exists"] = true,
  ["mark_here"] = true,
  ["mark_input_end"] = true,
  ["mark_input_start"] = true,
  ["mark_line"] = true,
  ["mark_match_end"] = true,
  ["mark_match_start"] = true,
  ["mark_pos"] = true,
  ["match_col"] = true,
  ["match_end_col"] = true,
  ["match_end_line"] = true,
  ["match_end_pos"] = true,
  ["match_group"] = true,
  ["match_groups"] = true,
  ["match_has"] = true,
  ["match_len"] = true,
  ["match_line"] = true,
  ["match_map"] = true,
  ["match_named"] = true,
  ["match_start_col"] = true,
  ["match_start_line"] = true,
  ["match_start_pos"] = true,
  ["match_text"] = true,
  ["matches"] = true,
  ["merge_hash"] = true,
  ["next"] = true,
  ["not"] = true,
  ["num_abs"] = true,
  ["num_add"] = true,
  ["num_avg"] = true,
  ["num_ceil"] = true,
  ["num_clamp"] = true,
  ["num_div"] = true,
  ["num_eq"] = true,
  ["num_floor"] = true,
  ["num_ge"] = true,
  ["num_gt"] = true,
  ["num_le"] = true,
  ["num_lt"] = true,
  ["num_max"] = true,
  ["num_median"] = true,
  ["num_min"] = true,
  ["num_mod"] = true,
  ["num_mul"] = true,
  ["num_ne"] = true,
  ["num_range"] = true,
  ["num_round"] = true,
  ["num_sub"] = true,
  ["num_sum"] = true,
  ["or"] = true,
  ["pick_keys"] = true,
  ["pop_back"] = true,
  ["pop_front"] = true,
  ["print"] = true,
  ["print_each"] = true,
  ["push"] = true,
  ["push_back"] = true,
  ["push_front"] = true,
  ["reduce_leaves"] = true,
  ["rename_key"] = true,
  ["replace_substr"] = true,
  ["restore_cursor"] = true,
  ["return"] = true,
  ["return_undef"] = true,
  ["reversed"] = true,
  ["rewind_entry_start"] = true,
  ["rewind_match_start"] = true,
  ["rm_prefix"] = true,
  ["rm_suffix"] = true,
  ["save_cursor"] = true,
  ["say"] = true,
  ["set"] = true,
  ["set_key"] = true,
  ["slice"] = true,
  ["sorted"] = true,
  ["sorted_keys"] = true,
  ["sorted_values"] = true,
  ["split"] = true,
  ["split_each"] = true,
  ["split_tagged_records"] = true,
  ["start_capture_slice"] = true,
  ["start_capture_slice_from"] = true,
  ["starts_with"] = true,
  ["str_eq"] = true,
  ["str_ge"] = true,
  ["str_gt"] = true,
  ["str_le"] = true,
  ["str_lt"] = true,
  ["str_ne"] = true,
  ["substr"] = true,
  ["switch"] = true,
  ["take"] = true,
  ["take_last"] = true,
  ["trim"] = true,
  ["trim_each"] = true,
  ["uniq"] = true,
  ["uppercase"] = true,
  ["uppercase_each"] = true,
  ["walk_leaves"] = true,
  ["while"] = true,
  ["with"] = true,
  ["+"] = true,
  ["-"] = true,
  ["*"] = true,
  ["/"] = true,
  ["%"] = true,
  ["=="] = true,
  ["!="] = true,
  [">"] = true,
  [">="] = true,
  ["<"] = true,
  ["<="] = true,
  ["abs"] = true,
  ["add"] = true,
  ["avg"] = true,
  ["ceil"] = true,
  ["clamp"] = true,
  ["div"] = true,
  ["eq"] = true,
  ["floor"] = true,
  ["ge"] = true,
  ["gt"] = true,
  ["le"] = true,
  ["lt"] = true,
  ["max"] = true,
  ["median"] = true,
  ["min"] = true,
  ["mod"] = true,
  ["mul"] = true,
  ["ne"] = true,
  ["range"] = true,
  ["round"] = true,
  ["sub"] = true,
  ["sum"] = true,
  ["="] = true,
  ["elif"] = true,
  ["i"] = true,
  ["otherwise"] = true,
  ["when"] = true,
}

-- Compatibility-only source spellings stay outside the shared 246-name
-- current inventory. They are accepted for migration and canonicalized by
-- action_contracts.lua before runtime dispatch.
local SOURCE_BOUNDARY_COMPATIBILITY_CALL_NAMES = {
  ["capture_from_rule_start"] = true,
  ["capture_len_from_rule_start"] = true,
  ["capture_rest_length"] = true,
  ["capture_slice_here"] = true,
  ["capture_slice_length"] = true,
  ["entry_named_map"] = true,
  ["match_named_map"] = true,
}

-- Exact contract view retained after FUTURE-PARITY-BACKLOG.17.5 admits these
-- names into CURRENT_CALL_NAMES. Keeping the governed family view avoids
-- reconstructing it from the larger shared inventory in focused tests.
local COMPLETE_NAMED_MARK_CALL_NAMES = {
  ["clear_mark"] = true,
  ["mark_col"] = true,
  ["mark_entry_end"] = true,
  ["mark_entry_start"] = true,
  ["mark_line"] = true,
  ["mark_match_end"] = true,
  ["mark_match_start"] = true,
}

-- Private rollout-only gap accessors are accepted by the Lua compiler and use
-- ordinary runtime dispatch, but deliberately stay outside the governed
-- 246-name shared ActionIR inventory until the outward-surface owner moves.
local PRIVATE_INTER_MATCH_GAP_CALL_NAMES = {
  ["entry_slot"] = true,
  ["gap_span"] = true,
  ["gap_text"] = true,
  ["gap_kind"] = true,
}

function M.is_known(name)
  return CURRENT_CALL_NAMES[name] == true or
    SOURCE_BOUNDARY_COMPATIBILITY_CALL_NAMES[name] == true or
    COMPLETE_NAMED_MARK_CALL_NAMES[name] == true or
    PRIVATE_INTER_MATCH_GAP_CALL_NAMES[name] == true
end

function M.is_shared_inventory_name(name)
  return CURRENT_CALL_NAMES[name] == true
end

function M.complete_named_mark_names()
  local result = {}
  for name in pairs(COMPLETE_NAMED_MARK_CALL_NAMES) do
    result[name] = true
  end
  return result
end

function M.count()
  local count = 0
  for _ in pairs(CURRENT_CALL_NAMES) do
    count = count + 1
  end
  return count
end

function M.current_names()
  local result = {}
  for name in pairs(CURRENT_CALL_NAMES) do
    result[#result + 1] = name
  end
  table.sort(result)
  return result
end

return M
