; Configure project inputs relative to the caller-selected design root.
(dc_load_cmd  dc_load_netlist)
(run_dir      .)
(ddc          design.ddc)

(cg_ids_enable      0)
(cg_id_patterns      HS65_LS_CNHLSX17)
;(cg_id_patterns      {HS65_LS_CNHLSX17|HS65_LH_CNOR2X17|HS65_LH_OR2X9})
(show_common_nodes  0)
