//! RUST-PARITY.7.1 — Perl↔Rust output-oracle fixture runner.
//!
//! Enumerates the language-neutral test corpus generated by
//! `tools/gen_oracle_corpus.pl` and asserts the Rust engine reproduces the Perl
//! reference output for every entry. This is the cross-variant parity gate: the
//! Perl reference is the behavioral oracle (ADR 0006), the corpus is its frozen
//! output, and `cargo test` validates the Rust backend against it with no Perl in
//! the loop.
//!
//! Corpus entry layout (one directory per case):
//!   tests/corpus/<case>/input.spec    — the .spec source (verbatim)
//!   tests/corpus/<case>/input.txt     — exact input bytes
//!   tests/corpus/<case>/expected.json — canonical reference (Perl) top-rule value
//!   tests/corpus/manifest.json        — intended fixture set and case count
//!
//! Output-shape rule (Perl↔Rust reconciliation): the Perl reference returns the
//! top rule's value directly, while the Rust engine wraps the accumulator one
//! level (`Engine::execute` returns `Array(accumulator)`). So `expected.json`
//! stores the backend-neutral reference value and this runner compares
//! `engine.execute(input) == json!([expected])`.

use linkedspec_core::compiler::compile;
use linkedspec_core::validation::validate;
use linkedspec_runtime::engine::Engine;
use linkedspec_runtime::spec_parser::parse_spec_with_user_functions;
use serde::Deserialize;
use serde_json::{Value, json};
use std::collections::BTreeSet;
use std::fs;
use std::path::{Path, PathBuf};

#[derive(Debug, Deserialize)]
struct CorpusManifest {
    format: u64,
    case_count: usize,
    cases: Vec<String>,
}

#[derive(Debug, PartialEq, Eq)]
struct CorpusDrift {
    missing: Vec<String>,
    extra: Vec<String>,
}

fn corpus_dir() -> PathBuf {
    Path::new(env!("CARGO_MANIFEST_DIR")).join("tests/corpus")
}

fn load_manifest(dir: &Path) -> CorpusManifest {
    let path = dir.join("manifest.json");
    let text = fs::read_to_string(&path)
        .unwrap_or_else(|e| panic!("cannot read corpus manifest {}: {e}", path.display()));
    let manifest: CorpusManifest = serde_json::from_str(&text)
        .unwrap_or_else(|e| panic!("malformed corpus manifest {}: {e}", path.display()));

    assert_eq!(
        manifest.format,
        1,
        "unsupported corpus manifest format {} in {}",
        manifest.format,
        path.display()
    );
    assert_eq!(
        manifest.case_count,
        manifest.cases.len(),
        "corpus manifest case_count={} does not match cases.len()={}",
        manifest.case_count,
        manifest.cases.len()
    );
    assert!(
        manifest.case_count > 0,
        "corpus manifest must name at least one fixture"
    );

    let case_set: BTreeSet<&str> = manifest.cases.iter().map(String::as_str).collect();
    assert_eq!(
        case_set.len(),
        manifest.cases.len(),
        "corpus manifest contains duplicate case names"
    );
    for name in &manifest.cases {
        assert!(
            !name.is_empty()
                && !name.contains('/')
                && !name.contains('\\')
                && name != "."
                && name != "..",
            "invalid corpus manifest case name: {name:?}"
        );
    }

    manifest
}

fn directory_case_names(dir: &Path) -> BTreeSet<String> {
    fs::read_dir(dir)
        .unwrap_or_else(|e| panic!("cannot read corpus dir {}: {e}", dir.display()))
        .filter_map(|e| e.ok())
        .map(|e| e.path())
        .filter(|p| p.is_dir())
        .map(|p| p.file_name().unwrap().to_string_lossy().to_string())
        .collect()
}

fn assert_manifest_matches_directories(dir: &Path, manifest: &CorpusManifest) {
    let expected: BTreeSet<String> = manifest.cases.iter().cloned().collect();
    let actual = directory_case_names(dir);

    if let Some(drift) = manifest_drift(&expected, &actual) {
        panic!(
            "oracle corpus manifest drift\n  missing fixture dirs: {:?}\n  extra fixture dirs: {:?}\nregenerate with `perl tools/gen_oracle_corpus.pl` and stage the manifest plus fixture dirs",
            drift.missing, drift.extra
        );
    }
}

fn manifest_drift(expected: &BTreeSet<String>, actual: &BTreeSet<String>) -> Option<CorpusDrift> {
    let missing: Vec<String> = expected.difference(&actual).cloned().collect();
    let extra: Vec<String> = actual.difference(&expected).cloned().collect();
    if missing.is_empty() && extra.is_empty() {
        None
    } else {
        Some(CorpusDrift { missing, extra })
    }
}

/// Run one corpus entry through parse → validate → compile → execute and return
/// `Err(message)` on any failure (so the runner can report every entry rather
/// than aborting on the first). The engine output must equal the reference value
/// wrapped one level (the Perl↔Rust output-shape rule).
fn run_entry(dir: &Path) -> Result<(), String> {
    let read = |file: &str| -> Result<String, String> {
        fs::read_to_string(dir.join(file)).map_err(|e| format!("cannot read {file}: {e}"))
    };
    let source = read("input.spec")?;
    let input = read("input.txt")?;
    let expected: Value = serde_json::from_str(&read("expected.json")?)
        .map_err(|e| format!("malformed expected.json: {e}"))?;

    let spec = parse_spec_with_user_functions(&source).map_err(|e| format!("parse failed: {e}"))?;
    validate(&spec).map_err(|e| format!("validate failed: {e}"))?;
    let compiled = compile(&spec).map_err(|e| format!("compile failed: {e}"))?;
    let engine = Engine::new(compiled);
    let actual = engine
        .execute(&input)
        .map_err(|e| format!("execute failed: {e}"))?;

    // Perl↔Rust output-shape rule: the Rust engine wraps the reference value one
    // level (the accumulator), so the expected engine output is `[ <reference> ]`.
    let wrapped = json!([expected]);
    if actual != wrapped {
        return Err(format!(
            "output mismatch on input {input:?}\n    expected (reference, wrapped): {}\n    actual   (engine.execute)    : {}",
            serde_json::to_string(&wrapped).unwrap(),
            serde_json::to_string(&actual).unwrap(),
        ));
    }
    Ok(())
}

#[test]
fn manifest_drift_guard_detects_missing_fixture_dir() {
    let expected = BTreeSet::from(["alpha".to_string(), "beta".to_string()]);
    let actual = BTreeSet::from(["alpha".to_string()]);

    assert_eq!(
        manifest_drift(&expected, &actual),
        Some(CorpusDrift {
            missing: vec!["beta".to_string()],
            extra: Vec::new(),
        })
    );
}

#[test]
fn manifest_drift_guard_detects_extra_fixture_dir() {
    let expected = BTreeSet::from(["alpha".to_string()]);
    let actual = BTreeSet::from(["alpha".to_string(), "stale".to_string()]);

    assert_eq!(
        manifest_drift(&expected, &actual),
        Some(CorpusDrift {
            missing: Vec::new(),
            extra: vec!["stale".to_string()],
        })
    );
}

#[test]
fn oracle_corpus_matches_perl_reference() {
    let dir = corpus_dir();
    assert!(
        dir.is_dir(),
        "corpus directory missing: {} (run `perl tools/gen_oracle_corpus.pl`)",
        dir.display()
    );

    let manifest = load_manifest(&dir);
    assert_manifest_matches_directories(&dir, &manifest);
    let entries: Vec<PathBuf> = manifest.cases.iter().map(|name| dir.join(name)).collect();

    // Report every entry, then fail once at the end if any diverged — so a single
    // run surfaces all parity gaps, not just the first.
    let mut failures: Vec<String> = Vec::new();
    let mut passed = 0;
    for entry in &entries {
        let name = entry.file_name().unwrap().to_string_lossy().to_string();
        match run_entry(entry) {
            Ok(()) => {
                println!("  PASS {name}");
                passed += 1;
            }
            Err(msg) => {
                println!("  FAIL {name}: {msg}");
                failures.push(format!("[{name}] {msg}"));
            }
        }
    }

    // The manifest is the drift guard: every intended fixture must be present
    // and no stale fixture directory may survive after a case is removed.
    // See docs/knowledge/rust-perl-output-oracle.md.
    assert!(
        passed == manifest.case_count,
        "runner executed {passed} fixtures, but manifest expects {}",
        manifest.case_count
    );
    assert!(
        failures.is_empty(),
        "oracle corpus has {} divergence(s):\n{}",
        failures.len(),
        failures.join("\n")
    );
}
