//! RUST-PARITY.7.1 — Perl↔Rust output-oracle fixture runner.
//!
//! Enumerates the language-neutral test corpus generated by
//! `tools/gen_oracle_corpus.pl` and asserts the Rust engine reproduces the Perl
//! reference output for every entry. This is the cross-variant parity gate: the
//! Perl reference is the behavioral oracle (ADR 0006), the corpus is its frozen
//! output, and `cargo test` validates the Rust backend against it with no Perl in
//! the loop.
//!
//! Corpus entry layout (one directory per case):
//!   tests/corpus/<case>/input.spec    — the .spec source (verbatim)
//!   tests/corpus/<case>/input.txt     — exact input bytes
//!   tests/corpus/<case>/expected.json — canonical reference (Perl) top-rule value
//!
//! Output-shape rule (Perl↔Rust reconciliation): the Perl reference returns the
//! top rule's value directly, while the Rust engine wraps the accumulator one
//! level (`Engine::execute` returns `Array(accumulator)`). So `expected.json`
//! stores the backend-neutral reference value and this runner compares
//! `engine.execute(input) == json!([expected])`.

use linkedspec_core::compiler::compile;
use linkedspec_core::parser::parse_spec;
use linkedspec_core::validation::validate;
use linkedspec_runtime::engine::Engine;
use serde_json::{json, Value};
use std::fs;
use std::path::{Path, PathBuf};

fn corpus_dir() -> PathBuf {
    Path::new(env!("CARGO_MANIFEST_DIR")).join("tests/corpus")
}

/// Run one corpus entry through parse → validate → compile → execute and return
/// `Err(message)` on any failure (so the runner can report every entry rather
/// than aborting on the first). The engine output must equal the reference value
/// wrapped one level (the Perl↔Rust output-shape rule).
fn run_entry(dir: &Path) -> Result<(), String> {
    let name = dir.file_name().unwrap().to_string_lossy().to_string();
    let read = |file: &str| -> Result<String, String> {
        fs::read_to_string(dir.join(file)).map_err(|e| format!("cannot read {file}: {e}"))
    };
    let source = read("input.spec")?;
    let input = read("input.txt")?;
    let expected: Value =
        serde_json::from_str(&read("expected.json")?).map_err(|e| format!("malformed expected.json: {e}"))?;

    let spec = parse_spec(&source).map_err(|e| format!("parse failed: {e}"))?;
    validate(&spec).map_err(|e| format!("validate failed: {e}"))?;
    let compiled = compile(&spec).map_err(|e| format!("compile failed: {e}"))?;
    let engine = Engine::new(compiled);
    let actual = engine.execute(&input).map_err(|e| format!("execute failed: {e}"))?;

    // Perl↔Rust output-shape rule: the Rust engine wraps the reference value one
    // level (the accumulator), so the expected engine output is `[ <reference> ]`.
    let wrapped = json!([expected]);
    if actual != wrapped {
        return Err(format!(
            "output mismatch on input {input:?}\n    expected (reference, wrapped): {}\n    actual   (engine.execute)    : {}",
            serde_json::to_string(&wrapped).unwrap(),
            serde_json::to_string(&actual).unwrap(),
        ));
    }
    Ok(())
}

#[test]
fn oracle_corpus_matches_perl_reference() {
    let dir = corpus_dir();
    assert!(
        dir.is_dir(),
        "corpus directory missing: {} (run `perl tools/gen_oracle_corpus.pl`)",
        dir.display()
    );

    let mut entries: Vec<PathBuf> = fs::read_dir(&dir)
        .unwrap_or_else(|e| panic!("cannot read corpus dir {}: {e}", dir.display()))
        .filter_map(|e| e.ok())
        .map(|e| e.path())
        .filter(|p| p.is_dir())
        .collect();
    entries.sort();

    // Report every entry, then fail once at the end if any diverged — so a single
    // run surfaces all parity gaps, not just the first.
    let mut failures: Vec<String> = Vec::new();
    let mut passed = 0;
    for entry in &entries {
        let name = entry.file_name().unwrap().to_string_lossy().to_string();
        match run_entry(entry) {
            Ok(()) => {
                println!("  PASS {name}");
                passed += 1;
            }
            Err(msg) => {
                println!("  FAIL {name}: {msg}");
                failures.push(format!("[{name}] {msg}"));
            }
        }
    }

    // .7.1 established the mechanism and a green first proof. The shipped recursive
    // specs are landing incrementally as the engine reaches parity: .7.5.1 (DONE)
    // fixed the header-line-regex → 0-regex compiler gap (a necessary prerequisite),
    // but tclite still needs .7.5.3 (action-edge fluent `.push`/`.return(...)`
    // lowering) and Lispish needs .7.5.2 (`scalaref(retv, {content})` parsing), so
    // those remain deferred from the committed corpus (which stays a controlled
    // green proof set). .7.2/.7.3 add structurally simple shipped specs; .7.4 adds
    // the full drift guard. See docs/knowledge/rust-perl-output-oracle.md.
    assert!(passed >= 1, "expected at least one green proof fixture, found {passed}");
    assert!(
        failures.is_empty(),
        "oracle corpus has {} divergence(s):\n{}",
        failures.len(),
        failures.join("\n")
    );
}
