export 'src/action/action_ast.dart'
    show
        ActionAccessSegment,
        ActionArgument,
        ActionArrayLiteralExpr,
        ActionAssignArrayAppendExpr,
        ActionAssignHashIndexExpr,
        ActionAssignNestedAccessExpr,
        ActionAssignScalarExpr,
        ActionBlock,
        ActionBlockValueExpr,
        ActionBooleanLiteralExpr,
        ActionCallExpr,
        ActionCodeblockArgumentExpr,
        ActionCodeblockLiteralErrorExpr,
        ActionCodeblockLiteralExpr,
        ActionContextualBlockSyntax,
        ActionContextualCodeblockCandidateExpr,
        ActionControlCaseExpr,
        ActionControlDefaultExpr,
        ActionControlElseExpr,
        ActionControlIfExpr,
        ActionControlMarkerExpr,
        ActionControlSwitchExpr,
        ActionControlWhileExpr,
        ActionExpr,
        ActionFluentCall,
        ActionFluentChainExpr,
        ActionHashLiteralEntry,
        ActionHashLiteralExpr,
        ActionIndexedVarExpr,
        ActionIndexAccessSegment,
        ActionKeyAccessSegment,
        ActionKeywordArgument,
        ActionNestedAccessExpr,
        ActionNode,
        ActionNumberLiteralExpr,
        ActionPositionalArgument,
        ActionRawExpr,
        ActionRegexLiteralExpr,
        RemovedAggregateSelector,
        ActionSourceSpan,
        ActionStatement,
        ActionStringLiteralExpr,
        ActionUndefExpr,
        ActionValueAccessExpr,
        ActionVariableExpr,
        findRemovedAggregateSelectorInBlock,
        findRemovedAggregateSelectorInExpr;
export 'src/action/action_contracts.dart'
    show
        ActionContractDiagnostic,
        ActionContractResolution,
        ActionResolvedContract,
        canonicalActionHelperName,
        completeNamedMarkActionIrCallNames,
        isKnownActionIrCallName,
        knownActionIrCallNames,
        resolveActionBlockContracts,
        resolveActionExpressionContracts,
        resolveActionStatementContracts,
        supportedActionIrCallNames;
export 'src/action/function_registry.dart'
    show
        UserFunctionCallResolution,
        UserFunctionEntry,
        UserFunctionRegistry,
        UserFunctionRegistryException;
export 'src/action/action_parser.dart'
    show parseActionBlock, parseActionExpression, parseActionStatement;
export 'src/ast/spec_ast.dart'
    show
        ActionEdgeBodyElementKind,
        BareEdgeBodyElementKind,
        BareEdgeTarget,
        BlindEdgeBodyElementKind,
        BodyElement,
        BodyElementKind,
        CallableSignature,
        CodeBlockBodyElementKind,
        ConditionalBodyElementKind,
        EdgeTarget,
        FluentCall,
        FluentChainBodyElementKind,
        FunctionDefinition,
        LifecycleMarkerBodyElementKind,
        PlainBlockBodyElementKind,
        RawBodyElementKind,
        RegexBodyElementKind,
        Rule,
        RuleHeader,
        RuleMode,
        SourceSpan,
        SpecFile,
        SplitMarkerBodyElementKind,
        StagedParseJob,
        StagedSourceSpan;
export 'src/compiler/compiled_spec.dart'
    show
        CompiledActionEdge,
        CompiledActionPayload,
        CompiledBlindEdge,
        CompiledDependencyRegexEntry,
        CompiledDependencyRegexState,
        CompiledDescriptorState,
        CompiledRegexSlotIdentity,
        CompiledRule,
        CompiledRuleModeMetadata,
        CompiledSpec,
        CompiledSpecException,
        DependencyRef,
        EntryRuleSelectionBasis,
        EntryRuleSelectionException,
        OrderedRegexSlotIdentityException,
        ResolvedEntryRule,
        assertOrderedRegexSlotIdentity,
        compiledRegexSlotIdentitiesFor,
        compileSpec,
        linkedSpecRegexSlotIdentityContract,
        linkedSpecRootRuleSelectionContract,
        validateCompiledRegexSlotIdentities,
        validateNoRemovedAggregateSelectors;
export 'src/corpus/manifest_runner.dart'
    show
        CorpusExecutionResult,
        CorpusFixture,
        CorpusFixtureExecutionResult,
        CorpusManifest,
        CorpusManifestException,
        CorpusValidationResult,
        executeCorpusFixtures,
        loadCorpusFixtures;
export 'src/io/spec_loader.dart'
    show
        LoadedCompiledSpec,
        LoadedSpec,
        ResolvedSpec,
        SpecCandidateOrigin,
        SpecLoadOptions,
        SpecPipelineCode,
        SpecPipelineException,
        SpecPipelineStage,
        SpecRequest,
        SpecRequestKind,
        loadAndCompileSpec,
        loadSpec,
        resolveSpec,
        validateSpecRequest;
export 'src/mcp/mcp_server.dart'
    show
        McpBudgetLimits,
        McpDeploymentPolicy,
        McpRegistrationOptions,
        McpServer,
        McpServerError;
export 'src/parser/spec_parser.dart' show SpecParseException, parseSpec;
export 'src/parser/staged_parser_registry.dart'
    show
        StagedFunctionBodyDispatchResult,
        StagedParseResult,
        StagedParserRegistryException,
        actionIrBodyAdapterDigest,
        actionIrBodyResolvedSpecId,
        actionIrBodySpecId,
        actionIrBodyTopRule,
        dispatchFunctionBodyParseJobs,
        executeStagedParseJob,
        executeStagedParseJobs,
        parseSpecWithStagedUserFunctionDefinitionAsts,
        stitchFunctionBodyParseJobs;
export 'src/parser/user_function_definition_shell.dart'
    show
        UserFunctionDefinitionProjection,
        parseSpecWithUserFunctionDefinitionAsts,
        projectUserFunctionDefinitionAsts;
export 'src/parser/user_function_definition_parser.dart'
    show
        UserFunctionDefinitionAstParser,
        UserFunctionDefinitionParserException,
        definitionNodesFromUserFunctionDefinitionOutput,
        parseSpecWithStagedUserFunctionDefinitions,
        parseUserFunctionDefinitionAsts,
        userFunctionDefinitionSpecRelativePath;
export 'src/runtime/matching.dart'
    show
        LineColumn,
        LinkedSpecParseMode,
        RuntimeMatchRegisters,
        RuntimeRegexAlternation,
        RuntimeRegexAlternative,
        RuntimeRegexMatch,
        charOffsetToCodeUnitOffset,
        codeUnitOffsetToCharOffset,
        lineColumnAtCodeUnitOffset;
export 'src/runtime/semantic_observation.dart'
    show
        RuntimeSemanticObservationEvent,
        RuntimeSemanticObservationEventKind,
        RuntimeSemanticObservationSink,
        linkedSpecSemanticExecutionObservationContract;
export 'src/runtime/interpreter.dart'
    show
        LinkedSpecRuntimeEngine,
        RuntimeDiagnostic,
        RuntimeDiagnosticOutputEvent,
        RuntimeDiagnosticOutputSink,
        RuntimeExitNow,
        RuntimeInterpreterException,
        RuntimeLifecycleEvent,
        RuntimeParseResult;
export 'src/runtime/generated_plan.dart'
    show GeneratedPlanRow, GeneratedRuleFamily;
export 'src/semantic/semantic_index.dart'
    show
        SemanticIndex,
        SemanticIndexError,
        SemanticIndexOptions,
        SemanticCompilationAuthority,
        SemanticCompilationDiagnostic,
        SemanticEntrySelection,
        SemanticGeneratedPlanInput,
        SemanticGeneratedPlanRow,
        SemanticQuery,
        SemanticQueryBudget,
        SemanticQueryCost,
        SemanticQueryDiagnostic,
        SemanticQueryDirection,
        SemanticQueryOperation,
        SemanticQueryPage,
        SemanticQueryPageState,
        SemanticQueryRecord,
        SemanticQueryRelation,
        SemanticQueryResponse,
        SemanticQuerySource,
        SemanticQuerySourceReference,
        SemanticSnapshot,
        SemanticSnapshotState,
        SemanticSourceDetail,
        SemanticSourceIdentity,
        SemanticSourceSpan;
export 'src/source_emitter.dart'
    show
        GeneratedSourceCode,
        GeneratedSourceException,
        GeneratedSourceMetadata,
        GeneratedSourceStage,
        buildGeneratedRulePlan,
        classifyGeneratedRuleFamily,
        emitDartSource,
        emitDartSourceV2,
        executeGeneratedParserV2,
        executeGeneratedParserWithTraceV2,
        linkedSpecGeneratedSourceContract,
        linkedSpecGeneratedSourceFormatVersion,
        validateGeneratedRulePlanV2,
        validateGeneratedSourceContractV2;
export 'src/scaffold.dart'
    show
        describeLinkedSpecDartScaffold,
        linkedSpecDartPackageName,
        linkedSpecDartScaffoldStatus;
export 'src/trace/trace.dart'
    show
        LinkedSpecTraceConfig,
        LinkedSpecTraceEmitter,
        LinkedSpecTraceEvent,
        LinkedSpecTraceEventKind,
        LinkedSpecTraceException,
        LinkedSpecTraceLevel,
        LinkedSpecTraceScope,
        LinkedSpecTraceSinkMode,
        linkedSpecTraceDumpDebug,
        linkedSpecTraceDumpFull,
        linkedSpecTraceDumpHigh,
        linkedSpecTraceDumpLow,
        linkedSpecTraceDumpMedium,
        linkedSpecTraceDumpNone;
export 'src/validation/spec_validator.dart'
    show SpecPortableDiagnostic, SpecValidationException, validateSpec;
