#!/usr/bin/env python3
"""Generate the filesystem-free Dart binding for the neutral MCP contract."""

from __future__ import annotations

import argparse
import hashlib

from mcp_contract_binding import GenerationError, ROOT, build_bundle, canonical_text, fail


OUTPUT_PATH = ROOT / "dart" / "lib" / "src" / "mcp" / "mcp_contract.dart"


def render_part(bundle: dict[str, object]) -> bytes:
    embedded = canonical_text(bundle)
    digest = hashlib.sha256(embedded.encode("utf-8")).hexdigest()
    delimiter = "'''"
    if delimiter in embedded:
        delimiter = '"""'
    if delimiter in embedded:
        fail("the canonical bundle cannot be represented by one Dart raw string")
    source = f'''// This file is generated by tools/generate_dart_mcp_contract.py.
// The neutral MCP artifacts are normative; do not edit this part by hand.

part of 'mcp_server.dart';

const _mcpBindingFormat = 1;
const _mcpBundleSha256 =
    '{digest}';
const _mcpBundleJson =
    r{delimiter}{embedded}{delimiter};
'''
    return source.encode("utf-8")


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--write", action="store_true", help="rewrite the committed generated part")
    args = parser.parse_args()
    expected = render_part(build_bundle())
    if args.write:
        OUTPUT_PATH.parent.mkdir(parents=True, exist_ok=True)
        OUTPUT_PATH.write_bytes(expected)
        print(f"generated {OUTPUT_PATH.relative_to(ROOT)} ({len(expected)} bytes)")
        return 0
    actual = OUTPUT_PATH.read_bytes() if OUTPUT_PATH.exists() else b""
    if actual != expected:
        fail(f"{OUTPUT_PATH.relative_to(ROOT)} is stale; run this tool with --write")
    print(f"Dart MCP contract binding is byte-fresh ({len(actual)} bytes)")
    return 0


if __name__ == "__main__":
    try:
        raise SystemExit(main())
    except GenerationError as exc:
        raise SystemExit(f"Dart MCP contract generation failed: {exc}") from exc
