#!/usr/bin/env python3
"""Generate the filesystem-free Rust binding for the neutral MCP contract."""

from __future__ import annotations

import argparse
import hashlib

from mcp_contract_binding import GenerationError, ROOT, build_bundle, canonical_text, fail


OUTPUT_PATH = ROOT / "rust" / "linkedspec-runtime" / "src" / "mcp_contract.rs"


def render_module(bundle: dict[str, object]) -> bytes:
    embedded = canonical_text(bundle)
    digest = hashlib.sha256(embedded.encode("utf-8")).hexdigest()
    hashes = "#"
    while f'"{hashes}' in embedded:
        hashes += "#"
    source = f'''// This file is generated by tools/generate_rust_mcp_contract.py.
// The neutral MCP artifacts are normative; do not edit this module by hand.

pub(crate) const BINDING_FORMAT: u32 = 1;
pub(crate) const BUNDLE_SHA256: &str =
    "{digest}";
pub(crate) const BUNDLE_JSON: &str = r{hashes}"{embedded}"{hashes};
'''
    return source.encode("utf-8")


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--write", action="store_true", help="rewrite the committed generated module")
    args = parser.parse_args()
    expected = render_module(build_bundle())
    if args.write:
        OUTPUT_PATH.write_bytes(expected)
        print(f"generated {OUTPUT_PATH.relative_to(ROOT)} ({len(expected)} bytes)")
        return 0
    actual = OUTPUT_PATH.read_bytes() if OUTPUT_PATH.exists() else b""
    if actual != expected:
        fail(f"{OUTPUT_PATH.relative_to(ROOT)} is stale; run this tool with --write")
    print(f"Rust MCP contract binding is byte-fresh ({len(actual)} bytes)")
    return 0


if __name__ == "__main__":
    try:
        raise SystemExit(main())
    except GenerationError as exc:
        raise SystemExit(f"Rust MCP contract generation failed: {exc}") from exc
