#!/usr/bin/env python3
"""Generate the filesystem-free Lua binding for the neutral MCP contract."""

from __future__ import annotations

import argparse
import hashlib

from mcp_contract_binding import GenerationError, ROOT, build_bundle, canonical_text, fail


OUTPUT_PATH = ROOT / "lua" / "src" / "linkedspec" / "mcp_contract.lua"


def long_bracket_delimiters(embedded: str) -> tuple[str, str]:
    """Return the least Lua long-bracket delimiter absent from the payload."""
    level = 0
    while True:
        equals = "=" * level
        opener = f"[{equals}["
        closer = f"]{equals}]"
        if closer not in embedded:
            return opener, closer
        level += 1


def render_module(bundle: dict[str, object]) -> bytes:
    embedded = canonical_text(bundle)
    digest = hashlib.sha256(embedded.encode("utf-8")).hexdigest()
    opener, closer = long_bracket_delimiters(embedded)
    source = f'''-- This file is generated by tools/generate_lua_mcp_contract.py.
-- The neutral MCP artifacts are normative; do not edit this module by hand.

return {{
  binding_format = 1,
  bundle_sha256 = "{digest}",
  bundle_json = {opener}{embedded}{closer},
}}
'''
    return source.encode("utf-8")


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--write", action="store_true", help="rewrite the committed generated module")
    args = parser.parse_args()
    expected = render_module(build_bundle())
    if args.write:
        OUTPUT_PATH.parent.mkdir(parents=True, exist_ok=True)
        OUTPUT_PATH.write_bytes(expected)
        print(f"generated {OUTPUT_PATH.relative_to(ROOT)} ({len(expected)} bytes)")
        return 0
    actual = OUTPUT_PATH.read_bytes() if OUTPUT_PATH.exists() else b""
    if actual != expected:
        fail(f"{OUTPUT_PATH.relative_to(ROOT)} is stale; run this tool with --write")
    print(f"Lua MCP contract binding is byte-fresh ({len(actual)} bytes)")
    return 0


if __name__ == "__main__":
    try:
        raise SystemExit(main())
    except GenerationError as exc:
        raise SystemExit(f"Lua MCP contract generation failed: {exc}") from exc
