#!/usr/bin/env python3
"""Generate the filesystem-free Julia binding for the neutral MCP contract."""

from __future__ import annotations

import argparse
import base64
import hashlib
import textwrap

from mcp_contract_binding import GenerationError, ROOT, build_bundle, canonical_text, fail


OUTPUT_PATH = ROOT / "julia" / "src" / "mcp" / "McpContract.jl"


def render_module(bundle: dict[str, object]) -> bytes:
    embedded = canonical_text(bundle).encode("utf-8")
    digest = hashlib.sha256(embedded).hexdigest()
    encoded = base64.b64encode(embedded).decode("ascii")
    chunks = textwrap.wrap(encoded, width=96)
    literals = "\n".join(f'    "{chunk}",' for chunk in chunks)
    source = f'''# This file is generated by tools/generate_julia_mcp_contract.py.
# The neutral MCP artifacts are normative; do not edit this file by hand.

const _MCP_BINDING_FORMAT = 1
const _MCP_BUNDLE_SHA256 = "{digest}"
const _MCP_BUNDLE_BASE64 = string(
{literals}
)
'''
    return source.encode("utf-8")


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--write", action="store_true", help="rewrite the committed generated module")
    args = parser.parse_args()
    expected = render_module(build_bundle())
    if args.write:
        OUTPUT_PATH.parent.mkdir(parents=True, exist_ok=True)
        OUTPUT_PATH.write_bytes(expected)
        print(f"generated {OUTPUT_PATH.relative_to(ROOT)} ({len(expected)} bytes)")
        return 0
    actual = OUTPUT_PATH.read_bytes() if OUTPUT_PATH.exists() else b""
    if actual != expected:
        fail(f"{OUTPUT_PATH.relative_to(ROOT)} is stale; run this tool with --write")
    print(f"Julia MCP contract binding is byte-fresh ({len(actual)} bytes)")
    return 0


if __name__ == "__main__":
    try:
        raise SystemExit(main())
    except GenerationError as exc:
        raise SystemExit(f"Julia MCP contract generation failed: {exc}") from exc
