#!/usr/bin/env python3
"""Generate the filesystem-free Perl binding for the neutral MCP contract.

The neutral JSON artifacts remain normative.  This tool verifies every digest
named by their manifest, composes the runtime subset into one canonical JSON
value, and either checks or rewrites the committed data-only Perl module.
"""

from __future__ import annotations

import argparse
import hashlib
from typing import Any

from mcp_contract_binding import GenerationError, ROOT, build_bundle, canonical_text, fail


OUTPUT_PATH = ROOT / "perl" / "LinkedSpec" / "MCPContract.pm"


def render_module(bundle: dict[str, Any]) -> bytes:
    embedded = canonical_text(bundle)
    digest = hashlib.sha256(embedded.encode("utf-8")).hexdigest()
    source = f'''# This file is generated by tools/generate_perl_mcp_contract.py.
# The neutral MCP artifacts are normative; do not edit this module by hand.
package LinkedSpec::MCPContract;

use 5.010;
use strict;
use warnings;
use utf8;

our $BINDING_FORMAT = 1;
our $BUNDLE_SHA256 = '{digest}';

my $BUNDLE_JSON = <<'LINKEDSPEC_MCP_CONTRACT_JSON';
{embedded}
LINKEDSPEC_MCP_CONTRACT_JSON
chomp $BUNDLE_JSON;

sub bundle_json {{ return $BUNDLE_JSON }}
sub bundle_sha256 {{ return $BUNDLE_SHA256 }}

1;
'''
    return source.encode("utf-8")


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--write", action="store_true", help="rewrite the committed generated module")
    args = parser.parse_args()
    expected = render_module(build_bundle())
    if args.write:
        OUTPUT_PATH.write_bytes(expected)
        print(f"generated {OUTPUT_PATH.relative_to(ROOT)} ({len(expected)} bytes)")
        return 0
    actual = OUTPUT_PATH.read_bytes() if OUTPUT_PATH.exists() else b""
    if actual != expected:
        fail(f"{OUTPUT_PATH.relative_to(ROOT)} is stale; run this tool with --write")
    print(f"Perl MCP contract binding is byte-fresh ({len(actual)} bytes)")
    return 0


if __name__ == "__main__":
    try:
        raise SystemExit(main())
    except GenerationError as exc:
        raise SystemExit(f"Perl MCP contract generation failed: {exc}") from exc
